[package]
name = "annparse"
version = "0.1.0"
authors = ["Greg Stamper <gastamper@gmail.com>"]

[dependencies]
reqwest = "0.9.20"
regex = "1"
clap = "2.33.0"
env_logger = "0.6.2"
log = "0.4.8"
flate2 = "1.0.11"
select = "0.4.3"
